### ISSUE TITLE
Ability to pass variables to playbooks from CSV at commandline

### ISSUE THREAD

**Issue by davidgower1** [mrlesmithjr/ansible-isc-dhcp#2]
I am looking for a way to pass all IP and host information from a variable file which would be loaded at run time. This file would be loaded when the playbook is run.  so the command would be "ansible-playbook buildPi.yml PiList.csv"  The buildPi.yml is the playbook which has the individual playbooks to install the various packages needed on the Raspberry Pi.  The PiList.csv would be a CSV variable list of the hostnames, IP addresses and Networks for each item needed in the playbooks.  That way we don't have to go in and change any of the playlists and run the risk of breaking them.

**Comment by mrlesmithjr** [comment]
In regards to this, I would recommend using defined variables for these lists. Do you have an example of what this CSV might look like, and we can see if we can put something together on what it would look like.

**Comment by davidgower1** [comment]
So each Pi needs five unique pieces of information, but they are really
derived from two sources.  The host name and IP address.  Here are the five
pieces

HostName, IPAddr, Network, DomainName, SSID

802629, 10.201.254.1, 10.201.254.0, 802629.local, 802629NTCAP

The Network is drived from the IP address.
The Domain Name and SSID are Derived from the HostName.
So really the CSV would only need to have two values for each devices we
are running the playbook against (hosts in the host file)

I need to set the IP address as a static on wlan1 after all is said and
done.

Host,IPAddr

I am using eth0 as the configuration interface and right now it is on DHCP
on a configuration network but I am going to set it with a bootstrap
program but that is a later issue, I want to get this tacked first.

Thanks in advance.


Regards,

David Gower
Cell 703-459-4800

**Comment by mrlesmithjr** [comment]
We can accomplish the info you would have in the CSV using YAML definitions for Ansible like so:
```yaml
---
net_devices:
  - host: 802629
    ip: 10.201.254.1
    network: 10.201.254.0
    domain: 802629.local
    ssid: 802629NTCAP
  - host: 802630
    ip: 10.201.254.2
    network: 10.201.254.0
    domain: 802630.local
    ssid: 802630NTCAP
```

Many of these bits can be templated out using Jinja2 when creating the configuration. I assume that you would like to define these in `/etc/dhcp/dhcpd.conf` as part of the statically defined IP assignments? I would recommend staying away from the CSV option if at all possible, however, you can checkout this blogpost on converting [CSV to YAML](https://everythingshouldbevirtual.com/automation/ansible-parsing-csv-list-hosts-ip-hostnames-mac/) on a possible option as well.

Hope this all makes sense.

**Comment by mrlesmithjr** [comment]
Also, keep in mind if this is functionality you are looking for, then we will need to make some code changes to account for this. I am not against that at all, assuming it provides additional use cases for others.

**Comment by davidgower1** [comment]
Thanks for all the very responsive help.  I have had team members who where
a cubicle away who where not a responsive!  I think I can take it from
here. As I said in my first email, I am new to Ansible and really needed
some direction.  You have done that and in spades!

Thanks again.  You have saved me and my team literally 100's of hours of
set up time with these scripts and playbooks for the next year or so!


Regards,

David Gower
Cell 703-459-4800

**Comment by mrlesmithjr** [comment]
Absolutely. Glad I could help and do let me know if you have any questions! And most of all, good luck and have fun!
